---
name: Build And Test CWMS Data API
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: build and test
    runs-on: ubuntu-latest
    outputs:
      thewar: ${{steps.thebuild.outputs.WARFILE}}
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: setup java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'
      - name: build and test
        id: thebuild
        run: ./gradlew build --info --init-script init.gradle
      - name: integration tests
        run: ./gradlew integrationtest --info --init-script init.gradle
      - name: Upload WAR
        uses: actions/upload-artifact@v4.4.3
        with:
          name: warfile
          path: cwms-data-api/build/libs/${{steps.thebuild.outputs.WARFILE}}
          retention-days: 1
          if-no-files-found: error
      - name: Build docker image
        run: docker build -t cda:build-latest .
