---
name: Release images and war
on:
  workflow_run:
    workflows: ["Build And Test CWMS Data API"]
    branches: ["develop"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Create and push releases
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: setup java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'
      - name: Download all workflow run artifacts from build
        id: artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: ./
      - name: get version
        id: get_version
        run: .github/workflows/get_version.sh
      - name: show version
        run: echo ${VERSION}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: warfile/${{ needs.build.outputs.thewar}}
          tag_name: ${{env.VERSION}}
          generate_release_notes: true
      - name: Login to Alt Registry
        uses: docker/login-action@v3.3.0
        id: login-alt
        with:
          registry: ${{ secrets.ALT_REGISTRY }}
          username: ${{ secrets.ALT_REG_USER }}
          password: ${{ secrets.ALT_REG_PASSWORD }}
      - name: Login to Alt Public Registry
        uses: docker/login-action@v3.3.0
        id: login-alt2
        with:
          registry: ${{ secrets.HEC_PUB_REGISTRY }}
          username: ${{ secrets.ALT_REG_USER }}
          password: ${{ secrets.ALT_REG_PASSWORD }}
      - name: Build docker image
        env:
          IMAGE_TAG: ${{env.VERSION}}
          ALT_REGISTRY: ${{secrets.ALT_REGISTRY}}
          HEC_PUB_REGISTRY: ${{secrets.HEC_PUB_REGISTRY}}
        run: |
          docker build -t cda:build-latest .
          docker tag cda:build-latest $ALT_REGISTRY/cwms/data-api:$IMAGE_TAG
          docker tag cda:build-latest $ALT_REGISTRY/cwms/data-api:latest
          docker tag cda:build-latest $HEC_PUB_REGISTRY/cwms/data-api:$IMAGE_TAG
          docker tag cda:build-latest $HEC_PUB_REGISTRY/cwms/data-api:latest
          docker push $ALT_REGISTRY/cwms/data-api:$IMAGE_TAG
          docker push $ALT_REGISTRY/cwms/data-api:latest
          docker push $HEC_PUB_REGISTRY/cwms/data-api:$IMAGE_TAG
          docker push $HEC_PUB_REGISTRY/cwms/data-api:latest
      - name: Logout of ALT registry
        if: ${{ always() }}
        run: |
          docker logout ${{ steps.login-alt.outputs.registry }}
          docker logout ${{ steps.login-alt2.outputs.registry }}
