---
name: Tagged Release
on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].[09][0-9].[0-9]'
      - '[0-9][0-9][0-9][0-9].[09][0-9].[0-9]-*+'
jobs:
  release:
    uses: ./.github/workflows/release.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      registry: ${{ secrets.HEC_PUB_REGISTRY}}
      registry_user: ${{ secrets.ALT_REG_USER }}
      registry_password: ${{ secrets.ALT_REG_PASSWORD }}
    with:
      branch: ${{github.ref_name}}
      nightly: false
